/**
 * memoryService — #227
 *
 * Two-level conversation context memory:
 *  1. Session memory (short-term)  — active conversation turns, reset after session ends.
 *     Already handled in-process by chatService.conversationStates; this service provides
 *     a session-summary written to Firestore when a session ends.
 *
 *  2. User memory (long-term)  — persistent user preferences and facts stored in Firestore.
 *     Injected into the system prompt on every request so Sylex "remembers" the user.
 *
 * Firestore schema:
 *   users/{uid}/memory/profile        — long-term user facts + preferences
 *   users/{uid}/sessions/{sessionId}  — session summary (written on session end)
 *
 * Graceful degradation: if Firebase Admin is unavailable (test / dev without SA),
 * all reads return empty and writes are skipped silently.
 */

import { createRequire } from 'module';
import logger from '../utils/logger.js';

const require = createRequire(import.meta.url);

let adminFirestore = null;

function getFirestore() {
  if (adminFirestore) return adminFirestore;
  try {
    const admin = require('firebase-admin');
    if (!admin.apps.length) return null;
    adminFirestore = admin.apps[0].firestore();
  } catch {
    adminFirestore = null;
  }
  return adminFirestore;
}

// ─── Long-term user memory ──────────────────────────────────────────────────

/**
 * Load the user's long-term memory profile from Firestore.
 * Returns an empty object when not found or when Firestore is unavailable.
 *
 * @param {string} uid  Firebase user UID
 * @returns {Promise<{facts: string[], preferences: Object}>}
 */
export async function loadUserMemory(uid) {
  if (!uid) return { facts: [], preferences: {} };
  const db = getFirestore();
  if (!db) return { facts: [], preferences: {} };
  try {
    const doc = await db.collection('users').doc(uid).collection('memory').doc('profile').get();
    if (!doc.exists) return { facts: [], preferences: {} };
    const data = doc.data();
    return {
      facts: Array.isArray(data.facts) ? data.facts : [],
      preferences: data.preferences && typeof data.preferences === 'object' ? data.preferences : {},
    };
  } catch (err) {
    logger.warn('memoryService: failed to load user memory', { uid, error: err.message });
    return { facts: [], preferences: {} };
  }
}

/**
 * Merge new facts / preferences into the user's long-term memory profile.
 * Deduplicates facts (case-insensitive). Merges preferences shallowly.
 *
 * @param {string}   uid
 * @param {Object}   update
 * @param {string[]} [update.facts]       - New facts to add (e.g. "User lives in Munich")
 * @param {Object}   [update.preferences] - Key-value preferences to merge
 */
export async function updateUserMemory(uid, { facts = [], preferences = {} } = {}) {
  if (!uid) return;
  const db = getFirestore();
  if (!db) return;
  try {
    const ref = db.collection('users').doc(uid).collection('memory').doc('profile');
    const existing = await ref.get();
    const current = existing.exists ? existing.data() : { facts: [], preferences: {} };
    const currentFacts = Array.isArray(current.facts) ? current.facts : [];
    const dedupedFacts = [
      ...currentFacts,
      ...facts.filter(f => !currentFacts.some(e => e.toLowerCase() === f.toLowerCase())),
    ].slice(-50); // cap at 50 facts to limit token usage
    await ref.set({
      facts: dedupedFacts,
      preferences: { ...(current.preferences || {}), ...preferences },
      updatedAt: new Date().toISOString(),
    }, { merge: true });
  } catch (err) {
    logger.warn('memoryService: failed to update user memory', { uid, error: err.message });
  }
}

// ─── Session summaries ──────────────────────────────────────────────────────

/**
 * Write a session summary to Firestore when a session ends.
 * The summary is a short string generated by the LLM or derived from the
 * conversation (caller is responsible for generating it).
 *
 * @param {string} uid
 * @param {string} sessionId
 * @param {string} summary   - Short text, e.g. "User asked about weather and navigation."
 * @param {Array}  messages  - Raw conversation turns [{role, content}]
 */
export async function saveSessionSummary(uid, sessionId, summary, messages = []) {
  if (!uid || !sessionId) return;
  const db = getFirestore();
  if (!db) return;
  try {
    await db
      .collection('users').doc(uid)
      .collection('sessions').doc(sessionId)
      .set({
        summary,
        turnCount: messages.filter(m => m.role === 'user').length,
        createdAt: new Date().toISOString(),
      });
  } catch (err) {
    logger.warn('memoryService: failed to save session summary', { uid, sessionId, error: err.message });
  }
}

// ─── Lightweight fact extraction ──────────────────────────────────────────────

// Regex patterns for common self-disclosures in user speech.
// Intentionally conservative to avoid false positives (e.g. "I think it's cold").
const FACT_PATTERNS = [
  /\bmy name is\s+(\w+)/i,
  /\bi(?:'m| am)\s+(?:called\s+)?(\w+)/i,
  /\bi live (?:in|near)\s+(.+?)(?:\.|,|$)/i,
  /\bi(?:'m| am) from\s+(.+?)(?:\.|,|$)/i,
  /\bi work (?:at|for|in)\s+(.+?)(?:\.|,|$)/i,
  /\bi(?:'m| am) a(?:n)?\s+(\w[\w\s]{0,30}?)(?:\.|,|$)/i,
  /\bi prefer\s+(.+?)(?:\.|,|$)/i,
  /\bi(?:'d| would) like\s+(.+?)(?:\.|,|$)/i,
  /\bmy (?:car|vehicle) is\s+(.+?)(?:\.|,|$)/i,
];

/**
 * Extract user facts from a single conversation turn using lightweight regex.
 * Returns at most a small number of fact strings to keep memory lean.
 *
 * @param {string} userText        - The user's message
 * @param {string} assistantText   - The assistant's reply (not used currently)
 * @returns {{ facts: string[], preferences: {} }}
 */
export function extractFactsFromTurn(userText, assistantText = '') {  // eslint-disable-line no-unused-vars
  const facts = [];
  for (const pattern of FACT_PATTERNS) {
    const match = userText.match(pattern);
    if (match) {
      // Capitalise first letter and trim to keep facts tidy
      const fact = match[0].trim().charAt(0).toUpperCase() + match[0].trim().slice(1);
      if (!facts.some(f => f.toLowerCase() === fact.toLowerCase())) {
        facts.push(fact);
      }
    }
  }
  return { facts, preferences: {} };
}

// ─── System-prompt injection ────────────────────────────────────────────────

/**
 * Build the user-memory section of the system prompt.
 * Returns an empty string when memory is empty so callers can check truthiness.
 *
 * @param {{facts: string[], preferences: Object}} memory
 * @returns {string}
 */
export function buildMemoryPromptSection(memory) {
  const parts = [];
  if (memory.facts?.length) {
    parts.push(`KNOWN USER FACTS:\n${memory.facts.map(f => `- ${f}`).join('\n')}`);
  }
  if (memory.preferences && Object.keys(memory.preferences).length) {
    const prefLines = Object.entries(memory.preferences)
      .map(([k, v]) => `- ${k}: ${v}`)
      .join('\n');
    parts.push(`USER PREFERENCES:\n${prefLines}`);
  }
  return parts.join('\n\n');
}
